CONFIG_GPIO=y

# Low power
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_RUNTIME_DEFAULT_ENABLE=y
CONFIG_PM_POLICY_DEFAULT=y
CONFIG_IDLE_STACK_SIZE=256
CONFIG_SYSTEM_TIMER_LPM_COMPANION_COUNTER=y
CONFIG_COUNTER=y
CONFIG_PM_PREWAKEUP_CONV_MODE_CEIL=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_SYSTEM_CLOCK_HW_CYCLES_PER_SEC_RUNTIME_UPDATE=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
#CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_SHELL=y
