CONFIG_MFD=y
CONFIG_MFD_MAX31790=y
CONFIG_PWM=y
CONFIG_PWM_MAX31790=y
CONFIG_SENSOR=y
CONFIG_MAX31790_FAN_SPEED=y
CONFIG_MAX31790_FAN_FAULT=y
CONFIG_I2C=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_PWM_INIT_PRIORITY=85
